config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :instruments do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :edit, :update, :destroy] do
    member do
      patch :approve
      patch :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
  enum status: { pending: 'pending', approved: 'approved', declined: 'declined' }
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :instruments
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @instrument = Instrument.find(params[:instrument_id])
    @booking = Booking.new
  end

  def create
    @instrument = Instrument.find(params[:instrument_id])
    @booking = @instrument.bookings.build(booking_params)
    @booking.user = current_user
    @booking.status = 'pending'
    if @booking.save
      redirect_to instrument_path(@instrument), notice: 'Booking created!'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.update(status: 'approved')
    redirect_to dashboard_path, notice: 'Booking approved'
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: 'declined')
    redirect_to dashboard_path, notice: 'Booking declined.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

  def index
    @instruments = Instrument.all
    if params[:city].present?
      @instruments = @instruments.where(city: params[:city])
    end

    if params[:name].present?
      @instruments = @instruments.where("name ILIKE ?", "%#{params[:name]}%")
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
    @name = @instrument.name
    @city = @instrument.city
    @description = @instrument.description
    @genre = @instrument.genre
    @city = @instrument.city
    @price = @instrument.price
    @available = @instrument.available
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user

    if @instrument.save
      redirect_to instruments_path, notice: "Instrument was successfully added!"
    else
      render :new
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def update
    @instrument = Instrument.find(params[:id])

    if @instrument.user == current_user
      if @instrument.update(instrument_params)
        redirect_to instrument_path(@instrument), notice: "Instrument was successfully updated!"
      else
        render :edit
      end
    else
      redirect_to instrument_path(@instrument), alert: "You don't have permission to edit this instrument"
    end
  end

  def destroy
    @instrument = Instrument.find(params[:id])

    if @instrument.user == current_user
      @instrument.destroy
      redirect_to dashboard_path, notice: "Instrument successfully deleted"
    else
      rredirect_to dashboard_path, alert: "You don't have permission to delete this instrument"
    end
  end

  private
  def instrument_params
    params.require(:instrument).permit(:name, :city, :description, :photo, :available, :price, :genre)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
  end

  def dashboard
    @bookings = current_user.bookings
    @requests = Booking.joins(:instrument).where(instruments: { user: current_user })
    @instruments = current_user.instruments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="main-container">
  <div class="left-container">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header bg-transparent border-0 text-center">
              <p id="bookform-title">Book <%= @instrument.name %> @<%= @instrument.city %></p>
            </div>
            <div class="card-body p-4">
              <%= form_for [@instrument, @booking], html: { class: 'form-horizontal' } do |f| %>

                <!-- Start Date Field -->
                <div class="form-group row">
                  <%= f.label :start_date, class: 'col-sm-3 col-form-label font-weight-bold' %>
                  <div class="col-sm-9">
                    <%= f.date_field :start_date, class: 'form-control', required: true %>
                  </div>
                </div>

                <!-- End Date Field -->
                <div class="form-group row">
                  <%= f.label :end_date, class: 'col-sm-3 col-form-label font-weight-bold' %>
                  <div class="col-sm-9">
                    <%= f.date_field :end_date, class: 'form-control', required: true %>
                  </div>
                </div>

                <!-- Additional fields go here -->

                <!-- Submit Button -->
                <div class="form-group row">
                  <div class="col-sm-9 offset-sm-3">
                    <%= f.submit 'Create Booking', class: 'button-27' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="right-container">
    <div class="carousel">
      <div class="carousel-cell">
        <img src="https://res.cloudinary.com/dhet05tdx/image/upload/v1692956781/guitar-player_b_w_gosali.jpg" class="carousel__img">
      </div>
      <div class="carousel-cell">
        <img src="https://res.cloudinary.com/dhet05tdx/image/upload/v1692960732/HD-wallpaper-a-crowd-at-a-concert_xeqz8a.jpg" class="carousel__img">
      </div>
      <div class="carousel-cell">
        <img src="https://res.cloudinary.com/dhet05tdx/image/upload/v1692960545/drums-black_and_white_pciesn.jpg" class="carousel__img">
      </div>
    </div>
  </div>
</div>

app/views/instruments/_form.html.erb
<%= simple_form_for @instrument, html: { class: "needs-validation", novalidate: "" } do |f| %>
  <div class="form-group">
    <%= f.input :name, label: "What instrument do you play?", required: true, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :city, required: true, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :description, required: true, input_html: { class: 'form-control', rows: '4' } %>
  </div>

  <div class="form-group">
    <%= f.input :photo, as: :file %>
    <small class="form-text text-muted">Upload an image of the instrument.</small>
  </div>

  <div class="form-group">
    <%= f.input :available, label: "Availability", required: true, input_html: { class: 'form-control' } %>
    <small class="form-text text-muted">Availability in minutes per day</small>
  </div>

  <div class="form-group">
    <%= f.input :price, required: true, input_html: { class: 'form-control', step: '0.01' } %>
    <small class="form-text text-muted">How much you charge per day</small>
  </div>

  <div class="form-group">
    <%= f.input :genre, required: true, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group mt-4">
    <%= f.button :submit, "Submit", class: "link" %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1 class="mb-4" id="h1-instrument">Edit an Instrument</h1>
<div class="container mt-5">
  <%= render 'form',
  instrument: @instrument %>
</div>
<div class="links_container">
  <div class="links">
    <%= link_to "Back to Instruments",
    instruments_path,
    class: "link" %>
    <%= link_to "Back to dashboard",
    dashboard_path,
    class: "link" %>
  </div>
</div>

app/views/instruments/index.html.erb
<h1 class="page-title">Musicians in <%= params[:city] %></h1>

<%= form_tag instruments_path, method: :get, class: "search-form" do %>
  <%= hidden_field_tag :city, params[:city] %>
  <%= text_field_tag :name, params[:name], placeholder: "Search for instrument...", class: "search-input" %>
  <%= submit_tag "Search", class: "search-button" %>
<% end %>



<div class="instrument-grid">
  <% @instruments.each do |instrument| %>
    <div class="instrument-card">
      <% if instrument.photo.attached? %>
          <%= cl_image_tag instrument.photo.key, class: "instrument-card__img", alt: instrument.name %>
      <% end %>
      <h2><%= instrument.name %></h2>
      <p class="text-show-page"><%= instrument.description %></p>
      <p>Posted by: <%= instrument.user.username %></p>
      <p><%= instrument.city %></p>
      <p>From price: <%= instrument.price %></p>

      <%= link_to "Check Instrument", instrument_path(instrument), class: "mr-2" %>
    </div>
  <% end %>
</div>


<div class="links_container">
  <div class="links">
    <%= link_to "Add a New Instrument", new_instrument_path, class: "link" %>
    <%= link_to "Back to Dashboard", dashboard_path, class: "link" %>
  </div
</div>

app/views/instruments/new.html.erb
<h1 class="mb-4" id="h1-instrument">Add a New Instrument</h1>
<div class="container mt-5">
  <%= render 'form',
  instrument: @instrument %>
</div>
<div class="links_container">
  <div class="links">
    <%= link_to "Back to Instruments",
    instruments_path,
    class: "link" %>
    <%= link_to "Back to dashboard",
    dashboard_path,
    class: "link" %>
  </div>
</div>

app/views/instruments/show.html.erb
<div class="show-container">
  <div class="show-row">
    <div class="show-col">
      <div class="show-card">
        <h1 class="show-title"><%= @name %></h1>
        <% if @instrument.photo.attached? %>
          <%= cl_image_tag @instrument.photo.key, class: "card-img-top", alt: @instrument.name %>
        <% end %>
      <div class="show-description">
          <p class="text_card"> City: <%= @city %></p>
          <p class="text_card"> Genre: <%= @genre %></p>
          <p class="text_card"> Description: <%= @description %></p>
          <p class="text_card"> Availability: <%= @available %> minutes/day</p>
          <p class="text_card"> Price: $<%= @price %></p>
          <div class="show-links-container">
            <% if current_user == @instrument.user %>
              <%= link_to "Edit", edit_instrument_path(@instrument), class: "show-link" %>
              <%= link_to "Delete", instrument_path(@instrument), data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "show-link" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="show-center">

        <% if user_signed_in? %>
          <%= link_to 'Book', new_instrument_booking_path(@instrument), class: 'show-link' %>
        <% else %>
          <%= link_to 'Log in to book this instrument', new_user_session_path, class: 'show-link' %>
        <% end %>
      </div>
        <div class="links_container">
          <div class="links">
          <%= link_to "Back to Instruments", instruments_path, class: 'link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sesh</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <!-- Flickity CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flickity/2.2.2/flickity.min.css">
    <!-- Flickity JavaScript -->
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flickity/2.2.2/flickity.pkgd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1 id="h1-sesh">Dashboard</h1>
<div class="main-container-dash">
  <div class="left-container-dash" data-controller="dashboard">
    <div class="headers-bookings">
      <button class="button-bookings" data-action="click->dashboard#toggleBookings"> Bookings </button>
      <button class="button-offers" data-action="click->dashboard#toggleOffers"> Offers </button>
    </div>

    <div data-dashboard-target="content" id="bookings">
      <h4> Accepted </h4>
      <hr>
      <% @bookings.select { |booking| booking.status == "approved" }.each do |booking| %>
      <div class="booking-container">
        <div class="booking-details">
          Instrument: <%= booking.instrument.name %><br>
          Start Date: <%= booking.start_date %><br>
          End Date: <%= booking.end_date %><br>
          Status: <%= booking.status %><br>
        </div>
        <div class="booking-delete">
          <%= link_to "×",
          booking_path(booking),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class: "delete-button" %>
        </div>
      </div>
      <hr>
      <% end %>

      <h4> Pending </h4>
      <hr>
      <% @bookings.select { |booking| booking.status == "pending" }.each do |booking| %>
      <div class="booking-container">
        <div class="booking-details">
          Instrument: <%= booking.instrument.name %><br>
          Start Date: <%= booking.start_date %><br>
          End Date: <%= booking.end_date %><br>
          Status: <%= booking.status %><br>
        </div>
        <div class="booking-delete">
          <%= link_to "×",
          booking_path(booking),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class: "delete-button" %>
        </div>
      </div>
      <hr>
      <% end %>
    </div>
    <div data-dashboard-target="content" id="offers" style="display: none;">
      <h4> Accepted </h4>
      <hr>
      <% @requests.select { |booking| booking.status == "approved" }.each do |booking| %>
        <div>
          Request by: <%= booking.user.username %><br>
          Instrument: <%= booking.instrument.name %><br>
          Start Date: <%= booking.start_date %><br>
          End Date: <%= booking.end_date %><br>
          Status: <%= booking.status %><br>
        </div>
        <hr>
      <% end %>

      <h4> Pending </h4>
      <hr>
      <% @requests.select { |booking| booking.status == "pending" }.each do |booking| %>
        <div id="container-pending">
          <div class="offer-details">
            Request by: <%= booking.user.username %><br>
            Instrument: <%= booking.instrument.name %><br>
            Start Date: <%= booking.start_date %><br>
            End Date: <%= booking.end_date %><br>
            Status: <%= booking.status %><br>
          </div>
          <div id="btn-offer-container">
            <%= button_to "Accept", approve_booking_path(booking), class: "btn-pending", method: :patch %>
            <%= button_to "Decline", decline_booking_path(booking), class: "btn-pending", method: :patch %>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>


  <div class="right-container-dash">
    <h2> Manage Instruments </h2>
    <div id="container-manage">
    <% @instruments.each do |instrument| %>
      <div class="instrument-container"> <!-- Added this class -->
        Instrument: <%= instrument.name %><br>
        Location: <%= instrument.city %><br>

        <div class="instrument-delete">
          <%= link_to "×", instrument_path(instrument), data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "delete-button" %>
        </div>
      </div>
      <hr>
    <% end %>
    </div>
  </div>
</div>

<div class="links_container">
  <div class="links">
    <%= link_to "Create Instrument", new_instrument_path, class: "link"  %>
    <%= link_to "Back to Instruments", instruments_path, class: "link"  %>
  </div>
  </div>

app/views/pages/home.html.erb
 <div class="main-container">
  <div class="left-container-land">
    <h1 id="h1-main">sesh</h1>
    <div class="container" data-controller="search">
      <div id="city-box">
        <h2>
          <span
          id="city-placeholder"
          data-search-target="placeholder"
          data-action="click->search#showSearch">
          Find Your City</span>

          <input
          type="text"
          id="search-city"
          data-search-target="search"
          data-action="click->search#showPlaceholder
          keyup->search#filter"
          placeholder="Find your city..."
          style="display: none;">
        </h2>

        <div id="city-list">
          <% Instrument.distinct.order(:city).pluck(:city).each do |city| %>
            <div data-search-target="city">
              <h3><%= link_to city, instruments_path(city: city), class: 'city-item' %></h3>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="right-container">
    <div class="carousel-landing slide" data-ride="carousel">
      <div class="carousel-inner-landing">
        <div class="carousel-item active" data-bs-interval="3000">
          <%= image_tag src="https://res.cloudinary.com/dzm55bol0/image/upload/v1692862928/bass_player_fvzk1g.jpg" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://res.cloudinary.com/dzm55bol0/image/upload/v1692946331/DALL_E_2023-08-25_00.06.39_-_black_and_white_profile_picture_musician_looking_into_camera_silhouette_alwe2r.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>